### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [snmateen/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by snmateen** [comment]
- [Syed Mateen] Your name
     - [Plano, Texas ] Where you are from
     - [Thai red curry] A favorite food
     - [Playing board games] A hobby
